POST http://localhost:3002/api/user/create
Content-Type: application/json

{
    "phone": "0939393939",
    "name": "test 39",
    "password": "123456789"
}

###
POST http://localhost:3002/api/auth/login
Content-Type: application/json

{
    "phone": "0123456789",
    "password": "12345678"
}

###
POST http://localhost:3002/api/auth/login
Content-Type: application/json

{
    "phone": "012345678",
    "password": "1234567"
}

###
POST http://localhost:3002/api/user/list

### 
POST http://localhost:3002/api/conversion/create
Content-Type: application/json

{
    "members": ["cvbccc", "svdsdv"],
    "type": "private"
}

###
GET http://localhost:3002/api/conversion/list/abc

###
POST http://localhost:3002/api/message/create
Content-Type: application/json

{
    "message": "ahihi"
}

###
POST http://localhost:3002/api/task/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODIxZDUxZTlhNzUzOWIxMjU5YjdjYyIsImlhdCI6MTY1MjY5NjQ0OCwiZXhwIjoxNjU1Mjg4NDQ4fQ.KaQ0qJG96RLpQymmqibIKp_weu3yWZ-Oo4zzVrxX45U

{
    "name": "ddd",
    "status": "approved"
}

### 
POST http://localhost:3002/api/task/update/6282368c0435f95f24395e76
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyODIxZDUxZTlhNzUzOWIxMjU5YjdjYyIsImlhdCI6MTY1MjY5NjQ0OCwiZXhwIjoxNjU1Mjg4NDQ4fQ.KaQ0qJG96RLpQymmqibIKp_weu3yWZ-Oo4zzVrxX45U

{
    "estimate_time": 1500,
    "assign": "62821d51e9a7539b1259b7cc",
    "status": "inprocess"
}

### 
GET http://localhost:3002/api/task/get/6282368c0435f95f24395e76

###
POST http://localhost:3002/api/task/list
Content-Type: application/json

{
}
